import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import GlobalProvider from "@/context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={`${poppins.className} antialiased`}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
