"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import GlobalProvider from "@/context";
import { usePathname } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const excludePath = [
    "/dashboard",
    "/dashboard/product",
    "/dashboard/sales",
    "/dashboard/transaction",
  ];
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={`${inter.className} antialiased`}>
          {pathname.includes(excludePath) && <Header />}
          {children}
        </body>
      </GlobalProvider>
    </html>
  );
}
