import "./globals.css";
import type { Metadata } from "next";
import GlobalProvider from "@/context";
import { Poppins } from "next/font/google";
import HeaderSideBar from "./HeaderSideBar";
import Container from "@/components/Container";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <GlobalProvider>
          <HeaderSideBar>{children}</HeaderSideBar>
        </GlobalProvider>
      </body>
    </html>
  );
}
